name: Deploy prod migrations
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Apply all pending migrations to the prod database
        run: npx prisma migrate deploy
        working-directory: ./apps/web
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
          DIRECT_URL: ${{ secrets.DIRECT_URL_PROD }}
