name: Deploy staging migrations
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Apply all pending migrations to the staging database
        run: npx prisma migrate deploy
        working-directory: ./apps/web
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
